FROM python:3.8

RUN mkdir /app
RUN cd /app
RUN pip install requests
RUN pip install pyyaml

RUN wget -q --no-check-certificate https://raw.githubusercontent.com/edklesel/Pi-Suite/master/Monitoring/DockMon/dockmon.py

CMD ["python3", "dockmon.py"]